services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=568
      - PGID=568
      - TZ=America/New_York
    volumes:
      - ./config:/config
      - /media:/media
    ports:
      - 8787:8787
    restart: unless-stopped
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=568
      - PGID=568
      - TZ=America/New_York
      - PASSWORD= #optional
      - CLI_ARGS= #optional
    volumes:
      - ./config:/config
      - /media:/media
    ports:
      - 8092:8080
      - 8181:8181
      - 8093:8081
    restart: unless-stopped
  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    environment:
      - PUID=568
      - PGID=568
      - TZ=America/New_York
    volumes:
      - ./config:/config
      - /media:/media
    ports:
      - 5000:5000
    restart: unless-stopped
