services:
  app:
    image: ghcr.io/hargata/lubelogger:latest
    build: .
    restart: unless-stopped
    # volumes used to keep data persistent
    volumes:
      - ./config:/App/config
      - ./data:/App/data
      - ./translations:/App/wwwroot/translations
      - ./documents:/App/wwwroot/documents
      - ./images:/App/wwwroot/images
      - ./temp:/App/wwwroot/temp
      - ./log:/App/log
      - ./keys:/root/.aspnet/DataProtection-Keys
    # expose port and/or use serving via traefik
    ports:
      - 8125:8080
